name: Subsplit

on:
    push:
        branches:
            - master

jobs:
    subsplit:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@master

            - name: Select PHP version
              uses: shivammathur/setup-php@master
              with:
                  php-version: '7.3'

            - name: Set GitHub Env
              run: git config --global user.password "${{ secrets.GITHUB_TOKEN }}"

            - name: Clone subsplit
              run: git clone https://github.com/dflydev/git-subsplit.git ~/subsplit

            - name: Install subsplit
              run: sudo cp ~/subsplit/git-subsplit.sh "$(git --exec-path)"/git-subsplit

            - name: Subsplit
              run: bash build/split.sh
