name: Subsplit

on:
    push:
        branches:
            - master

jobs:
    subsplit:
        runs-on: ubuntu-latest

        steps:
            - name: Install subsplit
              run: sudo cp ~/subsplit/git-subsplit.sh "$(git --exec-path)"/git-subsplit

            - name: Subsplit
              run: sudo bash build/split.sh
