name: Subsplit

on:
    push:
        branches:
            - master

jobs:
    subsplit:
        runs-on: ubuntu-latest

        steps:
            - name: Test 2
              run: ssh -T git@github.com

            - name: Install subsplit
              run: sudo cp ~/subsplit/git-subsplit.sh "$(git --exec-path)"/git-subsplit

            - name: Subsplit
              run: bash build/split.sh
